
// This file is automatically generated. Do not modify it manually.

import { initializeApp, getApps } from 'firebase/app';
import { getFirestore } from 'firebase/firestore';

const firebaseConfig = {
  projectId: "testmate-fkp41",
  appId: "1:333738741082:web:e19eb49beef45e94ed7763",
  storageBucket: "testmate-fkp41.firebasestorage.app",
  apiKey: "AIzaSyCBTCYZHBMy_cuKScJPV1R-pOOXewbMsUA",
  authDomain: "testmate-fkp41.firebaseapp.com",
  messagingSenderId: "333738741082",
};

// Initialize Firebase
let app;
if (!getApps().length) {
  app = initializeApp(firebaseConfig);
} else {
  app = getApps()[0];
}

const db = getFirestore(app);

export { db };
