
// This file is automatically generated. Do not modify it manually.

import { initializeApp, getApps, getApp } from 'firebase/app';
import { getFirestore } from 'firebase/firestore';
import { getAuth } from 'firebase/auth';


const firebaseConfig = {
  projectId: "testmate-fkp41",
  appId: "1:333738741082:web:e19eb49beef45e94ed7763",
  storageBucket: "testmate-fkp41.firebasestorage.app",
  apiKey: "AIzaSyCBTCYZHBMy_cuKScJPV1R-pOOXewbMsUA",
  authDomain: "testmate-fkp41.firebaseapp.com",
  messagingSenderId: "333738741082",
};

// Initialize Firebase
const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const db = getFirestore(app);
const auth = getAuth(app);


export { db, app, auth };
